name: Sky Betting & Gaming Engineering
markdown: kramdown
url: http://engineering.skybettingandgaming.com
host: 0.0.0.0
gems:
    - jekyll-feed
    - jekyll-paginate
paginate: 5
paginate_path: "/:num/"
kramdown:
    input: GFM
    syntax_highlighter: rouge
exclude:
    [vendor]