name: Sky Betting & Gaming Engineering
markdown: kramdown
url: http://engineering.skybettingandgaming.com
host: 0.0.0.0
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-feed
kramdown:
    input: GFM
    syntax_highlighter: rouge
exclude:
    [vendor]
